# Generated by Django 5.2 on 2025-04-20 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_viewed_workout_end_time_workout_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 23, 5, 6, 590202, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 23, 5, 17, 451894, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
