# Generated by Django 5.2 on 2025-04-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_workout_end_time_alter_workout_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesschallenge',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='api.workout'),
        ),
        migrations.AddField(
            model_name='fitnessevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
