# Generated by Django 5.0.2 on 2025-04-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fitnesschallenge_workouts_fitnessevent_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='tp',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('muscle', 'Muscle'), ('flexibility', 'Flexibility'), ('strength', 'Strength'), ('functional', 'Functional'), ('circuit', 'Circuit'), ('other', 'Other')], max_length=20),
        ),
    ]
