# Generated by Django 5.0.2 on 2025-04-27 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnesschallenge",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="challenges_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
