from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from . import views
from .views import (
    UserListCreateView, UserDetailView,
    FriendListView, FriendCreateView,
    AnnouncementListView, AnnouncementCreateView,
    FriendRequestListView, FriendRequestCreateView,
    MessageReceivedListView, MessageSentListView, MessageCreateView,
    FitnessEventListView, FitnessEventUserListView, FitnessEventCreateView, FitnessEventDetailView,
    FitnessChallengeListView, FitnessChallengeUserListView, FitnessChallengeCreateView,
    FlaggedAIMessageListView,
    WorkoutListView, CustomAuthToken, MessageMarkAsViewedView, BatchUserLookupView, BatchWorkoutLookupView, FriendRequestAcceptView, FriendRequestDeclineView, FriendDeleteView, FitnessEventUpdateView, FitnessEventDeleteView, FitnessChallengeUpdateView, FitnessChallengeDeleteView, FitnessChallengeDetailView, UserWorkoutCreateView, UserWorkoutListView, UserUpdateView, ChangePasswordView, 
)

urlpatterns = [
    path('login/', CustomAuthToken.as_view(), name='api_token_auth'),
    path('users/create', UserListCreateView.as_view(), name='user-list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('users/<int:pk>/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('friends/<int:user_id>/', FriendListView.as_view(), name='friend-list'),
    path('friends/<int:friend_id>/delete', FriendDeleteView.as_view(), name='friend-list'),
    path('announcements/', AnnouncementListView.as_view(), name='announcement-list'),
    path('announcements/create/', AnnouncementCreateView.as_view(), name='announcement-create'),
    path('friend-requests/<int:user_id>/', FriendRequestListView.as_view(), name='friend-request-list'),
    path('friend-requests/create/', FriendRequestCreateView.as_view(), name='friend-request-create'),
    path('friend-requests/<int:pk>/accept/', FriendRequestAcceptView.as_view(), name='friend-request-accept'),
    path('friend-requests/<int:pk>/decline/', FriendRequestDeclineView.as_view(), name='friend-request-decline'),
    path('messages/received/<int:user_id>/', MessageReceivedListView.as_view(), name='message-received-list'),
    path('messages/sent/<int:user_id>/', MessageSentListView.as_view(), name='message-sent-list'),
    path('fitness-events/', FitnessEventListView.as_view(), name='fitness-event-list'),
    path('fitness-events/<int:event_id>/', FitnessEventDetailView.as_view(), name='fitness-event-detail'),
    path('fitness-events/user/<int:user_id>/', FitnessEventUserListView.as_view(), name='fitness-event-user-list'),
    path('fitness-events/create/', FitnessEventCreateView.as_view(), name='fitness-event-create'),
    path('fitness-events/<int:event_id>/update/', FitnessEventUpdateView.as_view(), name='fitness-event-update'),
    path('fitness-events/<int:event_id>/delete/', FitnessEventDeleteView.as_view(), name='fitness-event-delete'),
    path('fitness-challenges/', FitnessChallengeListView.as_view(), name='fitness-challenge-list'),
    path('fitness-challenges/<int:challenge_id>/', FitnessChallengeDetailView.as_view(), name='fitness-event-detail'),
    path('fitness-challenges/user/<int:user_id>/', FitnessChallengeUserListView.as_view(), name='fitness-challenge-user-list'),
    path('fitness-challenges/create/', FitnessChallengeCreateView.as_view(), name='fitness-challenge-create'),
    path('fitness-challenges/<int:challenge_id>/update/', FitnessChallengeUpdateView.as_view(), name='fitness-challenge-update'),
    path('fitness-challenges/<int:challenge_id>/delete/', FitnessChallengeDeleteView.as_view(), name='fitness-challenge-delete'),
    path('flagged-ai-messages/<int:user_id>/', FlaggedAIMessageListView.as_view(), name='flagged-ai-message-list'),
    path('workouts/<int:user_id>/', WorkoutListView.as_view(), name='workout-list'),
    path('workouts/batch/', BatchWorkoutLookupView.as_view(), name='batch-workout-lookup'),
    path('messages/<int:pk>/mark-as-viewed/', MessageMarkAsViewedView.as_view(), name='message-mark-as-viewed'),
    path('messages/create/', MessageCreateView.as_view(), name='message-create'),
    path('users/batch/', BatchUserLookupView.as_view(), name='batch-user-lookup'),
    path('user-workouts/create', UserWorkoutCreateView.as_view(), name='user-workout-create'),
    path('user-workouts/<int:user_id>/', UserWorkoutListView.as_view(), name='user-workout-list'),
    path('workouts/create/', views.WorkoutCreateView.as_view(), name='workout-create'),
    path('strava/login/', views.strava_login, name='strava_login'),
    path('strava/callback/', views.strava_callback, name='strava_callback'),
    path('strava/latest-activity/', views.strava_latest_activity, name='strava-latest-activity'),
]